export const config = {
  title: "Qemat Al-Najah",
  description: "Qemat Alnajah",
  url: "https://qemat-alnajah.vercel.app",
  author: "Qemat Alnajah",
  ogImage: "https://qemat-alnajah.vercel.app/og.png",
  mainEmail: "info@qemat-alnajah.com.iq",
  facebookURL: "https://facebook.com/qemat-alnajah",
  mainMenu: [
    { title: "Home", path: "#home" },
    { title: "About", path: "#about" },
    { title: "Services", path: "#services" },
    { title: "Contact us", path: "#contact" },
  ],
  specialties: [
    "Construction",
    "Medical Support Services",
    "Supply Contracting",
    "Trading",
    "Contracting",
    "Electronics and Devices",
    "Electrical Supplies & Modern Lighting",
    "Apparel for All",
    "Supporting the Displaced (UN)",
    "Logistical Expertise",
    "Food Items",
    "None-Food Items",
    "Rental Services",
    "Manpower & Packaging",
  ],
  seoTitle: "QEMAH AL-NAJAH Co. | General Trading & Supply Contracting.",
  seoDescription:
    "Qemah Al-Najah Co. It is the name behind many Iraq’s most advanced and prestigious facilities. The company was established in 1998. And it is headquartered in Baghdad. Over the years, the group has un- retaken many challenging projects and accumulated skills.",
};
